webui:
    image: gajjelli/nodejs-emp:latest
    container_name: employee
    ports:
        - 8888
    hostname: employee
    links:
        - mongodb:mongo

mongodb:
    image: mongo
    container_name: mongo
    ports:
        - 27017
    hostname: mongo
    volumes:
        - $HOME/mongo/data/db:/data/db
